armor_detector_opencv:
  ros__parameters:
    use_sim_time: true
    debug: true
    camera_name: "front_industrial_camera"

    detect_color: 0
    binary_thres: 80

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.25
    ignore_classes: ["negative"]

armor_detector_openvino:
  ros__parameters:
    use_sim_time: true
    use_sensor_data_qos: true
    debug_mode: true
    detect_color: 0

    detector:
      camera_name: "front_industrial_camera"
      subscribe_compressed: false

      # Model
      model_path: $(find-pkg-share armor_detector_openvino)/model/opt-1208-001.onnx
      device_type: "AUTO"
      confidence_threshold: 0.98
      top_k: 128
      nms_threshold: 0.3

armor_tracker:
  ros__parameters:
    use_sim_time: true
    target_frame: chassis
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 0.0004
      r_yaw: 0.003

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      tracking_thres: 5
      lost_time_thres: 1.0

projectile_motion:
  ros__parameters:
    use_sim_time: true
    projectile:
      offset_pitch: 0.0
      offset_yaw: 0.0
      offset_time: 0.08
      initial_speed: 18.0
      target_frame: "gimbal_pitch"              # gimbal frame_id
      target_topic: "tracker/target"
      gimbal_cmd_topic: "cmd_gimbal"
      shoot_cmd_topic: "cmd_shoot"
      solver_type: "gravity"                    # projectile solve method: gravity / gaf
      # friction: 0.001                         # Air resistance factor if use GAF solver
